### ISSUE TITLE
notebook doesn't launch from my binder

### ISSUE THREAD

**Issue by smrgeoinfo** [earthcube2021/ec21_bourgault_etal#1]
Click on 'launch Binder' link from https://earthcube2021.github.io/ec21_book/notebooks/ec21_bourgault_etal/README.html.  Log runs for awhile, get error
```
+ conda run -n finch-demo python -m pip install git+https://github.com/bird-house/finch.git@hot-fix-no-stdout#egg=finch
ERROR conda.cli.main_run:execute(33): Subprocess for 'conda run ['python', '-m', 'pip', 'install', 'git+https://github.com/bird-house/finch.git@hot-fix-no-stdout#egg=finch']' command failed.  (See above for error)
  Running command git clone -q https://github.com/bird-house/finch.git /tmp/pip-install-n_su7g7r/finch_df070f45000440c0b4f37164fcf63fb2
  WARNING: Did not find branch or tag 'hot-fix-no-stdout', assuming revision or ref.
  Running command git checkout -q hot-fix-no-stdout
  error: pathspec 'hot-fix-no-stdout' did not match any file(s) known to git.
WARNING: Discarding git+https://github.com/bird-house/finch.git@hot-fix-no-stdout#egg=finch. Command errored out with exit status 1: git checkout -q hot-fix-no-stdout Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement finch (unavailable) (from versions: 0.3.2, 0.3.3)
ERROR: No matching distribution found for finch (unavailable)
```
...
then
`The command '/bin/sh -c ./.binder/postBuild' returned a non-zero code: 1`

and process stops.

**Comment by aulemahal** [comment]
@smrgeoinfo Thanks for notifying us! And sorry about this dumb bug. I just fixed it by pulling a newer version of finch. There was a problem with pandas and xarray also, fixed that too.

**Comment by smrgeoinfo** [comment]
Thanks!  notebook loads now, and runs.
I did get some errors :
"/srv/conda/envs/notebook/lib/python3.7/site-packages/dask/utils.py:35: RuntimeWarning: All-NaN slice encountered
  return func(*args, **kwargs)"
from the cell that starts with 'out.first_day_below.plot(hue='realization', color='grey', alpha=0.5)', but the plot still came up. Not sure if this is expected.
